import django.forms
import django.forms.fields
import fields
import django_form_architect.settings
from django.template.defaultfilters import slugify


class AutoGeneratedForm(django.forms.Form):
    
    def __init__(self, form_model, *args, **kwargs):
        super(AutoGeneratedForm, self).__init__(*args, **kwargs)
        for page in form_model.page_set.all():
            for widget in page.widget_set.all():
                widget_field = fields.WidgetFieldFactory.from_widget(widget)                                
                self.fields['{0}-{1}'.format(slugify(widget.label) ,str(widget.pid))] = widget_field
                
    def is_valid(self, *args, **kwargs):
        super(AutoGeneratedForm, self).is_valid(*args, **kwargs)
        if self.errors:
            for field_name in self.fields:
                if field_name in self.errors:
                    classes = self.fields[field_name].widget.attrs.get('class', '')
                    classes += ' error'
                    self.fields[field_name].widget.attrs['class'] = classes